apiVersion: v1
kind: ConfigMap
metadata:
  name: sorter-simulator-config
  namespace: default
data:
  ZoneSimulatorConfig__Zone: "sorter"
  ZoneSimulatorConfig__ItemsSource: "src"
  ZoneSimulatorConfig__ItemsDestination: "end"
  ZoneSimulatorConfig__NumConveyors: "2"
  ZoneSimulatorConfig__ConveyorTransitMilliseconds: "0"
  ZoneSimulatorConfig__InterConnectionDelayMilliseconds: "0"
  MqttConfig__MqttServer: "4.233.145.224"
  MqttConfig__MqttPort: "1884"
  MqttConfig__QoS: "1"
  MqttConfig__TrackStatus: "true"
  MqttConfig__ClientId: "Mqtt.SorterSimulator"
  MqttConfig__Username: "<SECRET>"
