apiVersion: v1
kind: Pod
metadata:
  name: mqtt-client3-pub-transf
  namespace: pubsub-tests
spec:
  containers:
  - name: mqtt-client3-pub-transf
    image: ragcdevacr.azurecr.io/mqttechoclient:latest
    envFrom:
    - configMapRef:
        name: mqtt-client3-pub-transf-config
  restartPolicy: OnFailure
  imagePullSecrets:
  - name: ragcdevacr-pull-secret  
---
apiVersion: v1
kind: Pod
metadata:
  name: mqtt-client5-sub-transf
  namespace: pubsub-tests
spec:
  containers:
  - name: mqtt-client5-sub-transf
    image: ragcdevacr.azurecr.io/mqttechoclient:latest
    envFrom:
    - configMapRef:
        name: mqtt-client5-sub-transf-config
  restartPolicy: OnFailure
  imagePullSecrets:
  - name: ragcdevacr-pull-secret    