apiVersion: v1
kind: PersistentVolume
metadata:
  name: emqx-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/emqx/data/mnesia"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi