apiVersion: v1
kind: Pod
metadata:
  name: zone-simulator-shp
  namespace: default
spec:
  containers:
  - name: zone-simulator-shp
    image: ragcdevacr.azurecr.io/sim/zonesimulator:latest
    envFrom:
    - configMapRef:
        name: zone-simulator-shp-config
    - secretRef:
        name: simulation-secrets               
  restartPolicy: OnFailure
  imagePullSecrets:
  - name: ragcdevacr-pull-secret