apiVersion: v1
kind: ConfigMap
metadata:
  name: zone-simulator-shp-config
  namespace: default
data:
  ZoneSimulatorConfig__Zone: "shp"
  ZoneSimulatorConfig__SourceZone: "int"
  ZoneSimulatorConfig__DestinationZone: "end"
  ZoneSimulatorConfig__NumConveyors: "3"
  ZoneSimulatorConfig__ConveyorTransitMilliseconds: "5000"
  ZoneSimulatorConfig__InterConnectionDelayMilliseconds: "0"
  MqttConfig__MqttServer: "iot-pocs-sim-1"
  MqttConfig__MqttPort: "1883"
  MqttConfig__QoS: "1"
  MqttConfig__TrackStatus: "true"
  MqttConfig__ClientId: "Mqtt.ZoneSimulator.Shp"
  MqttConfig__Username: "client1"