apiVersion: v1
kind: Pod
metadata:
  name: hive2-pub
  namespace: pubsub-tests
spec:
  containers:
  - name: hive2-pub
    image: ragcdevacr.azurecr.io/mqttechoclient:latest
    envFrom:
    - configMapRef:
        name: hive2-pub-config
  restartPolicy: OnFailure
  imagePullSecrets:
  - name: ragcdevacr-pull-secret
---
apiVersion: v1
kind: Pod
metadata:
  name: hive4-sub
  namespace: pubsub-tests
spec:
  containers:
  - name: hive4-sub
    image: ragcdevacr.azurecr.io/mqttechoclient:latest
    envFrom:
    - configMapRef:
        name: hive4-sub-config
  restartPolicy: OnFailure
  imagePullSecrets:
  - name: ragcdevacr-pull-secret